version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: react-client
    ports:
      - "80:80"  
    environment:
      - VITE_API_BASE_URL=http://18.233.156.168:8080
    networks:
      - appnet
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  

networks:
  appnet:
    driver: bridge
